version: "2.1"
services:
  webreactjs:
    build:
      context: ./
      dockerfile: web.dockerfile
    depends_on:
      - servergo
    ports:
      - 3000:3000
    tty: true
  servergo:
    build:
      context: ./
      dockerfile: app.dockerfile
    ports:
      - 8080:8080
    restart: always
